GET http://localhost:5000/api/v1/catalog

###

POST http://localhost:5000/api/v1/catalog

Content-Type: application/json

{
     "TenLoaiSanPham": "demooo",
    "TenDanhMuc": "demooo",
    "Key": "te-demooo",
    "AnHien": false,
    "ThuTuSapXep": 1,
}