export const GET_LIST_COMMENTID = "GET_LIST_COMMENTID";
export const GET_LIST_COMMENTID_SUCCESS = "GET_LIST_COMMENTID_SUCCESS";

export const POST_COMMENT = "POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
