export const GET_LIST_ORDERID = "GET_LIST_ORDERID";
export const GET_LIST_ORDERID_SUCCESS = "GET_LIST_ORDERID_SUCCESS";

export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
