export const GET_LIST_RATEID = "GET_LIST_RATEID";
export const GET_LIST_RATEID_SUCCESS = "GET_LIST_RATEID_SUCCESS";

export const POST_RATE = "POST_RATE";
export const POST_RATE_SUCCESS = "POST_RATE_SUCCESS";
