export const GET_LIST_CONTACT = "GET_LIST_CONTACT";
export const GET_LIST_CONTACT_SUCCESS = "GET_LIST_CONTACT_SUCCESS";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
