export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER";
export const GET_LIST_CUSTOMER_SUCCESS = "GET_LIST_CUSTOMER_SUCCESS";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";

export const LOGIN_CUSTOMER = "LOGIN_CUSTOMER";
export const LOGIN_CUSTOMER_SUCCESS = "LOGIN_CUSTOMER_SUCCESS";

export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";

export const INFO_CUSTOMER = "INFO_CUSTOMER";
export const INFO_CUSTOMER_SUCCESS = "INFO_CUSTOMER_SUCCESS";

export const PASS_CUSTOMER = "PASS_CUSTOMER";
export const PASS_CUSTOMER_SUCCESS = "PASS_CUSTOMER_SUCCESS";
