export const GET_LIST_ORDER = "GET_LIST_ORDER";
export const GET_LIST_ORDER_SUCCESS = "GET_LIST_ORDER_SUCCESS";

export const GET_DETAIL_ORDER = "GET_DETAIL_ORDER";
export const GET_DETAIL_ORDER_SUCCESS = "GET_DETAIL_ORDER_SUCCESS";

export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
