export const GET_LIST_STAFF = "GET_LIST_STAFF";
export const GET_LIST_STAFF_SUCCESS = "GET_LIST_STAFF_SUCCESS";

export const LOGIN_STAFF = "LOGIN_STAFF";
export const LOGIN_STAFF_SUCCESS = "LOGIN_STAFF_SUCCESS";

export const REGISTER_STAFF = "REGISTER_STAFF";
export const REGISTER_STAFF_SUCCESS = "REGISTER_STAFF_SUCCESS";
